public class DemoRecord {

  public static void main(String[] args) {
    Dog dog = new Dog("Buddy", 3);
    System.out.println(dog.name());
    System.out.println(dog.age());
    // No setter method, cannot change the value of name and age

    // equals, toString, hashCode are automatically generated by the compiler
    Dog dog2 = new Dog("Buddy", 3);
    System.out.println(dog.equals(dog2)); // true
    System.out.println(dog); // Dog[name=Buddy, age=3]

  }
  // ! Java 16 (Record)
  public static record Dog(String name, int age) {
    
  }

  public static void sleep(String name) {
    System.out.println(name + " is sleeping...");
  }

  public double area() {
    return 0.0;
  }

  @Override
  public String toString() {
    return "DemoRecord{}";
  }
  
}
